### ISSUE TITLE
Incorrect resolution for 240V systems

### ISSUE THREAD

**Issue by retrodaredevil** [jorticus/pymate#10]
https://github.com/jorticus/pymate/blob/683479776fff26480fe6d28928725dfc984aada8/pymate/matenet/fx.py#L342-L363

I noticed that for 240V systems, the resolution of the returned `Value` instance was always 0 decimal places. If the system is 240V, I think the resolution should be 1 decimal place because you're dividing by 2, which means that the result could be something like 1.5, but is actually interpreted as 1.0.

**Comment by jorticus** [comment]
Good catch, I'll test it out

**Comment by jorticus** [comment]
Note that this is purely cosmetic - the resolution parameter is used for formatting the string, but the full accuracy is still there if you convert to float.
