### ISSUE TITLE
scan.py: RuntimeError: Error parsing struct - invalid length (Got 4 bytes, expected 2)

### ISSUE THREAD

**Issue by two9ers** [jorticus/pymate#22]
Hi Jordan, My system (2004 vintage) consists of two FX, two MX, and a MATE. When running scan.py, the hub and two FX are detected, but it errors on detecting the MX devices. Any insights are most welcome. Thanks for your work on this!. Jim

MATE Bus Scan
Port0: Hub (Rev: 001.000.001)
Port1: FX (Rev: 000.000.000)
Port2: FX (Rev: 000.000.000)
Traceback (most recent call last):
  File "scan.py", line 76, in <module>
    print_device(subdev)
  File "scan.py", line 36, in print_device
    dtype = d.scan()
  File "/home/pi/pymate-master/pymate/matenet/matedevice.py", line 38, in scan
    return self.matenet.scan(self.port)
  File "/home/pi/pymate-master/pymate/matenet/matenet.py", line 169, in scan
    result = self.query(0x00, port=port)
  File "/home/pi/pymate-master/pymate/matenet/matenet.py", line 136, in query
    response = MateNET.QueryResponse.from_buffer(resp)
  File "/home/pi/pymate-master/pymate/cstruct.py", line 64, in from_buffer
    raise RuntimeError("Error parsing struct - invalid length (Got %d bytes, expected %d)" % (data_len, cls._size))
RuntimeError: Error parsing struct - invalid length (Got 4 bytes, expected 2)

The debug output when it  detects the 2nd FX on Port2 and tries Port3:

Send [Port2, Type=0x02, Addr=0x0004, Param=0x0000]
TX: [1] 02
TX: [0] 02 00 04 00 00 00 08
RX: 02 00 00 00 02
Port2: FX (Rev: 000.000.000)
Send [Port3, Type=0x02, Addr=0x0000, Param=0x0000]
TX: [1] 03
TX: [0] 02 00 00 00 00 00 05
RX: 00 00 02 11 03 00 16

**Comment by jorticus** [comment]
Thank you for the debug logs.
It looks like there are some extra null bytes (00h) being received in response to the Port 3 scan command. If you skip 2 bytes you get "02 11 03 00 16" which is what I'd expect for an MX device. (11=Unknown byte, 03=MX, 16=Checksum=02+11+03)

Could you try adding a delay to [scan.py line 36](https://github.com/jorticus/pymate/blob/master/scan.py#L36)?
```python
def print_device(d):
    dtype = d.scan()
    time.sleep(0.1)  # Add a delay
```
This might help tell us if these extra bytes are coming in at the wrong time.

If that doesn't work, try flushing the serial port in case the extra bytes are leftover from a previous command:
```python
def print_device(d):
    bus.port.ser.flushInput()  # Flush the serial port
    dtype = d.scan()
```

**Comment by two9ers** [comment]
Well I tried those individually and together with no success. Do we have to get into cstruct.py and shed the first two bytes when the validation fails?

    # Length validation
    data_len = len(data)
    if data_len != cls._size:
        raise RuntimeError("Error parsing struct - invalid length (Got %d bytes, expected %d)" % (data_len, cls._size))

**Comment by jorticus** [comment]
I don't think that's the right solution here. That error is a side effect of receiving too many bytes in the first place...

I think what's happening is that some extra bytes or noise on the bus is coming in before the 9th bit is set (indicating start of packet), but due to the "hacky" implementation of 9-bit serial we can't enforce this and so the library just starts the packet at the first received byte even if the 9th bit was not set. 

I expect if you use the PJON transport and an Arduino (which can do true 9 bit data) you wouldn't encounter this problem, however this is trickier to set up.

As a workaround (not sure if this will work in all cases), I modified matenet.py#L136 to truncate the buffer before parsing. I pushed it to branch `issue-22` so please check it out and give it a try (`git fetch; git checkout -t origin/issue-22`). 
```
        resp = self.send(MateNET.TYPE_QUERY, addr=reg, param=param, port=port)
        if resp:
            response = MateNET.QueryResponse.from_buffer(resp[-MateNET.QueryResponse._size:])
            return response.value
```

**Comment by two9ers** [comment]
Success!

MATE Bus Scan
Port0: Hub (Rev: 001.000.001)
Port1: FX (Rev: 000.000.000)
Port2: FX (Rev: 000.000.000)
Port3: MX (Rev: 11265.044.000)
Port4: MX (Rev: 11273.044.000)

Now to move on to readout.py
Thank you for your time on this, what a great resource you have provided!
