### ISSUE TITLE
Test FLEXnet DC unit

### ISSUE THREAD

**Issue by jorticus** [jorticus/pymate#5]
I now have a FLEXnet DC unit in hand. This task will track my progress in testing the unit.

**Comment by joshuajayg** [comment]
Any updates on this enhancement?  I'd be interested in helping with a homemade shunt monitor that can act like a FlexNetDC.

**Comment by jorticus** [comment]
Finally got around to looking into this - it basically works the same as other Mate devices:
```
> py2 .\testflexnet.py
MATE emulator (FLEXnet DC)
Revision: 001.001.071
Status:
RAW[1]: 01 00 00 00 00 00 00 64 00 00 00 00 00 00 01 21 00 01 00 00 00 01 00 00 00 00 00 00
RAW[2]: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00 00
```
The RJ45 pinout is the same as the MX/FX devices, except GND is not connected. It uses BAT- as the GND. It draws 90mA @ 24V.

I haven't yet decoded the status packet or know what commands you can send to it. I'm a little stuck without a MATE unit to probe. The User Guide mentions that you need to configure it through the MATE (to set things like which channels are enabled, the nominal battery voltage, etc).

If anyone has a MATE and would like to help out with this reverse engineering effort, shoot me an e-mail! Otherwise I'll dig deeper next time I visit my holiday house.

(Some preliminary code is pushed onto the branch [feature/flexnetdc](/jorticus/pymate/tree/feature/flexnetdc))

**Comment by jorticus** [comment]
@joshuajayg I have added support for the FLEXnet DC. See tester.py for how you could emulate your own FLEXnet, or check out [DeviceEmulator.ino](https://github.com/jorticus/uMATE/blob/master/examples/DeviceEmulator/DeviceEmulator.ino) in my uMATE project.

**Comment by joshuajayg** [comment]
Thanks, I'll check it out.  I was just reading through your pull request.  I think I'm having trouble with my optocoupler circuit so I still have to fix that.  I'll give it a shot soon.

**Comment by joshuajayg** [comment]
Up and running.  I don't have an FX inverter so I am not sure if your testflexnet.py will function.  I haven't tried it yet but will get to it late this week.  Do you know how the charge controller reads net amperage from the FlexNetDC to decide when to move to float?  That is my most desired feature.

**Comment by jorticus** [comment]
Do you have a source in the guide for where that feature is mentioned? As far as I'm aware the devices do not talk to each other (all communication is strictly MATE -> Device)

**Comment by jorticus** [comment]
You also don't require an FX to utilize the FLEXnet DC code, though it does require at least an MX charge controller to provide power.

**Comment by joshuajayg** [comment]
I guess I mean the FlexNet should tell the MATE when charge parameters are met then the MATE tells the MX to move on to float.  There are some references but it is mostly convoluted. 

Check this thread:  https://forum.solar-electric.com/discussion/350802/outback-fm80-end-amps-vs-flexnet-return-amps#Comment_358586
And this thread: http://www.outbackpower.com/forum/viewtopic.php?f=28&t=6253
Which mentions this thread: http://www.outbackpower.com/forum/viewtopic.php?f=17&t=6233
And provides this manual: 
[23nfi4pn40hq.pdf](https://github.com/jorticus/pymate/files/4409445/23nfi4pn40hq.pdf)  (Check page 6)


So if the net amperage (to the batteries) calculated by the FlexNet meets the "End Amps" parameter set in the MATE, then the MATE should send a "Force_Float" signal to the MX charge controller to stop the absorb charge.  Generally, people's discussions seem to indicate this is a lacking feature in the Outback system but but your project "spoofing" the MATE can solve that.

I guess the only real feature I need to implement that is what data is sent to the MX charge controller to force float?

**Comment by joshuajayg** [comment]
Added issue #18 to deal with this.
