### ISSUE TITLE
readout.py - MX_PORT is not defined

### ISSUE THREAD

**Issue by joshuajayg** [jorticus/pymate#7]
Seeing you closed an issue got me interested in the project again.  readout.py does not work though.
Even when following your instructions in the Readme.md, there are issues with the port but that should probably be on a different issue.

```
pi@raspberrypi3_2:~/pymate $ python readout.py
MATE emulator (MX)
Traceback (most recent call last):
  File "readout.py", line 11, in <module>
    mate = MateMXDevice(bus, port=MX_PORT)
NameError: name 'MX_PORT' is not defined
```

**Comment by jorticus** [comment]
My bad, it was a typo. Fixed in f3b9d17.
If you are using a hub, you will need to specify the port, otherwise you can leave it out so it defaults to port 0 (no hub).

Please do file another bug if you're seeing other issues.
