### ISSUE TITLE
No response - MX

### ISSUE THREAD

**Issue by joshuajayg** [jorticus/pymate#8]
Still unable to communicate with the charge controller.  I have tested my optocoupler at system voltages and it works fine though I do not have a scope.

When using readout.py or setting up communication manually I get the timeout error.

```
>>> mate_mx.scan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "matenet/mx.py", line 138, in scan
    raise RuntimeError("No response from the MX unit")
RuntimeError: No response from the MX unit
```

**Comment by jorticus** [comment]
Hi, please try the latest code, and enable full debug logs:

``` python
log = logging.getLogger('mate')
log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler())
```

See: scan.py

**Comment by joshuajayg** [comment]
Played with this today.  Got it working.  I didn't have to mess with the code at all, I just had to troubleshoot my optocoupler circuit for a couple hours.  I am receiving packets now and readout.py works fine.

**Comment by jorticus** [comment]
Great to hear!

**Comment by oriolism** [comment]
> Played with this today. Got it working. I didn't have to mess with the code at all, I just had to troubleshoot my optocoupler circuit for a couple hours. I am receiving packets now and readout.py works fine.

Hi @joshuajayg, Can you tell me what steps you took to troubleshoot the octocoupler? My Flexmax 80 is not detected when i run the scan.py file.
